### ISSUE TITLE
Footer not showing on bottom of pages

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#104]
The footer is not showing at the absolute bottom of the page. See screenshot. Footer is showing in a different place on each page (looks relative to content but not to window height)
![screen shot 2015-01-26 at 11 13 01 am](https://cloud.githubusercontent.com/assets/6717960/5904216/94f6e962-a54c-11e4-923e-b025df646d9c.png)

**Comment by benwilhelm** [comment]
That's by design. It's actually rather complex to get a footer to stick to the bottom of the page when the content is less than the height of the window, but flow to the bottom when it overflows. I limited the width of the footer so it matches the content width, which makes it appear a little less out of place.

http://mybuildingdoesntrecycle.com/about

Is that a satisfactory solution?

**Comment by matiaskitty** [comment]
That looks good to me. Thanks much.
