### ISSUE TITLE
Contact page - include both Contact Form and MailTo Link

### ISSUE THREAD

**Issue by matiaskitty** [open-city/recycling#82]
On the Contact page, include a mailto link under the contact form. I know it seems weird to include both, but Contact Forms are better for desktop users who haven't specified an email client, and mailto links are better for mobile users because they don't have to type in email addresses, names etc. See: http://www.justinmind.com/contact

You can see it in the wireframes here:
http://i785tr.axshare.com/contact.html

**Comment by benwilhelm** [comment]
I put it in like the mockup:

http://mybuildingdoesntrecycle.com/contact

But I would suggest that if we're doing this for the benefit of the mobile user, we put the link at the top of the page rather than the bottom. That way mobile users will see that first and know immediately that they don't need to fill out the contact form.  What do you think?

**Comment by alexkahn** [comment]
We can just hide the form for mobile viewports and make the link a button that appears for mobile view only.

**Comment by matiaskitty** [comment]
Making the link a button for mobile viewports sounds like a good solution.

**Comment by alexkahn** [comment]
On it.

**Comment by alexkahn** [comment]
Fixed with 51517cd9d40620e08177efdd0c5c9ed337addda8 and there was a little extra stuff in there too.
